#!/usr/bin/env python3
"""Carve the EL daemon out of the Zed workspace.

Usage: standalone.py <repo_root> <out_dir>

Copies crates/el_engine, crates/el_worker, crates/el_serve into <out_dir>
and writes a minimal Cargo.toml workspace for them: only the
[workspace.dependencies] those crates actually reference, the shared
lints, the release profile, and the repo's Cargo.lock (Cargo prunes it
to what the subset uses, keeping the same versions). Building there
never touches the IDE's dependency graph.
"""
import shutil
import sys
import tomllib
from pathlib import Path

EL_CRATES = ["el_engine", "el_worker", "el_serve"]


def toml_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{key} = {toml_value(item)}" for key, item in value.items()) + " }"
    raise TypeError(f"unsupported TOML value: {value!r}")


def referenced_workspace_deps(crate_dir: Path) -> set[str]:
    manifest = tomllib.loads((crate_dir / "Cargo.toml").read_text())
    names: set[str] = set()
    for section in ("dependencies", "dev-dependencies", "build-dependencies"):
        for name, spec in manifest.get(section, {}).items():
            if isinstance(spec, dict) and spec.get("workspace"):
                names.add(name)
    for target in manifest.get("target", {}).values():
        for section in ("dependencies", "dev-dependencies", "build-dependencies"):
            for name, spec in target.get(section, {}).items():
                if isinstance(spec, dict) and spec.get("workspace"):
                    names.add(name)
    return names


def main(repo_root: str, out_dir: str) -> None:
    repo = Path(repo_root)
    out = Path(out_dir)
    root_manifest = tomllib.loads((repo / "Cargo.toml").read_text())
    workspace = root_manifest["workspace"]
    all_deps = workspace["dependencies"]

    out.mkdir(parents=True, exist_ok=True)
    (out / "crates").mkdir(exist_ok=True)
    needed: set[str] = set()
    for crate in EL_CRATES:
        src = repo / "crates" / crate
        dst = out / "crates" / crate
        if dst.exists():
            shutil.rmtree(dst)
        # The crates' LICENSE-* files are symlinks to the repo root; in a
        # partial checkout (the Docker build context) they dangle.
        shutil.copytree(
            src,
            dst,
            ignore=shutil.ignore_patterns("target"),
            ignore_dangling_symlinks=True,
        )
        needed |= referenced_workspace_deps(src)

    lines = ["# Generated by deploy/el-serve/standalone.py — the EL daemon on its own.", ""]
    lines.append("[workspace]")
    lines.append('resolver = "2"')
    lines.append("members = [" + ", ".join(f'"crates/{crate}"' for crate in EL_CRATES) + "]")
    lines.append("")
    lines.append("[workspace.dependencies]")
    for name in sorted(needed):
        if name not in all_deps:
            raise SystemExit(f"{name} is referenced as a workspace dependency but not defined")
        spec = all_deps[name]
        if isinstance(spec, dict) and "path" in spec:
            # Sibling EL crate: point at the copied one.
            spec = dict(spec)
            spec["path"] = "crates/" + Path(spec["path"]).name
        lines.append(f"{name} = {toml_value(spec)}")
    lines.append("")
    lints = workspace.get("lints", {})
    for table, entries in lints.items():
        lines.append(f"[workspace.lints.{table}]")
        for key, value in entries.items():
            lines.append(f"{key} = {toml_value(value)}")
        lines.append("")
    release = root_manifest.get("profile", {}).get("release")
    if release:
        lines.append("[profile.release]")
        for key, value in release.items():
            if isinstance(value, dict):
                continue  # per-package overrides belong to the IDE build
            lines.append(f"{key} = {toml_value(value)}")
        lines.append("")
    (out / "Cargo.toml").write_text("\n".join(lines))
    shutil.copy2(repo / "Cargo.lock", out / "Cargo.lock")
    for license in ("LICENSE-GPL", "LICENSE-APACHE"):
        if (repo / license).is_file():
            shutil.copy2(repo / license, out / license)
    # Pin the same compiler as the IDE (the lockfile's crates need it),
    # without the IDE's extra targets/components.
    toolchain = tomllib.loads((repo / "rust-toolchain.toml").read_text())["toolchain"]
    (out / "rust-toolchain.toml").write_text(
        f'[toolchain]\nchannel = "{toolchain["channel"]}"\nprofile = "minimal"\n'
    )
    print(f"standalone EL workspace at {out} ({len(needed)} workspace deps)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
