//! The Oracle loader sidecar: drives the engine's Oracle [`Session`] —
//! Oracle's pure-Rust thin driver, or the thick ODPI-C driver for a 10g /
//! 11g target — from this worker process. Same JSON-lines protocol as the
//! Snowflake and DuckDB loaders; every statement it runs is generated by
//! `el_engine::load::oracle_sql` on the parent side.
//!
//! Chunks arrive as Arrow IPC files and are array-bound through the
//! parent's `INSERT … VALUES (:1, :2, …)`: one batch per chunk, every
//! cell typed from its column's dtype (a NULL carries the type too, so an
//! all-NULL column cannot fix the wrong one). The password comes from the
//! environment (`ZDBT_EL_ORACLE_PASSWORD`) and never appears in a request
//! or an error.

use std::io::BufRead as _;

use anyhow::{Context as _, Result, anyhow, bail};
use chrono::{DateTime, NaiveDate};
use el_engine::connectors::oracle::{Cell, CellKind, Session, connect};
use el_engine::load::protocol::{ENV_ORACLE_PASSWORD, Request, Response};
use el_engine::polars::prelude::*;

fn respond(response: &Response) {
    if let Ok(line) = serde_json::to_string(response) {
        println!("{line}");
    }
}

pub fn serve() -> Result<()> {
    let stdin = std::io::stdin();
    let mut connection: Option<Session> = None;

    for line in stdin.lock().lines() {
        let line = line.context("reading stdin")?;
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        let request: Request = match serde_json::from_str(trimmed) {
            Ok(request) => request,
            Err(error) => {
                respond(&Response::error(format!("bad request: {error}")));
                continue;
            }
        };
        match request {
            Request::Shutdown => {
                respond(&Response::ok());
                break;
            }
            Request::OpenOracle {
                user,
                connect_string,
            } => match open(&user, &connect_string) {
                Ok(conn) => {
                    connection = Some(conn);
                    respond(&Response::ok());
                }
                Err(error) => respond(&Response::error(format!("{error:#}"))),
            },
            Request::Exec { sql } => match &connection {
                Some(conn) => respond(
                    &exec(conn, &sql).unwrap_or_else(|error| Response::error(format!("{error:#}"))),
                ),
                None => respond(&Response::error("not connected — send open first")),
            },
            Request::QueryScalar { sql } => match &connection {
                Some(conn) => respond(
                    &query_scalar(conn, &sql)
                        .unwrap_or_else(|error| Response::error(format!("{error:#}"))),
                ),
                None => respond(&Response::error("not connected — send open first")),
            },
            Request::IngestOracle {
                insert_sql,
                ipc_path,
            } => match &connection {
                Some(conn) => respond(
                    &ingest(conn, &insert_sql, &ipc_path)
                        .unwrap_or_else(|error| Response::error(format!("{error:#}"))),
                ),
                None => respond(&Response::error("not connected — send open first")),
            },
            Request::Open { .. } | Request::OpenDuckdb { .. } | Request::Ingest { .. } => {
                respond(&Response::error(
                    "this is the oracle loader — snowflake and duckdb requests go to \
                     snowflake-loader and duckdb-loader",
                ));
            }
        }
    }
    Ok(())
}

/// Connects with the password the parent put in our environment, on the
/// driver it named. The session it returns already pins TIME_ZONE=UTC and
/// a dot decimal separator, which the timestamp binds and the watermark
/// read-back rely on.
fn open(user: &str, connect_string: &str) -> Result<Session> {
    let password = std::env::var(ENV_ORACLE_PASSWORD)
        .with_context(|| format!("{ENV_ORACLE_PASSWORD} is not set in the sidecar environment"))?;
    connect(user, &password, connect_string)
}

fn exec(session: &Session, sql: &str) -> Result<Response> {
    let rows_affected = session.execute(sql)?;
    // DDL and PL/SQL blocks commit themselves; DML does not.
    session.commit()?;
    let mut response = Response::ok();
    response.rows_affected = Some(rows_affected);
    Ok(response)
}

fn query_scalar(session: &Session, sql: &str) -> Result<Response> {
    let mut response = Response::ok();
    response.scalar = session.query_scalar_text(sql)?.map(serde_json::Value::String);
    Ok(response)
}

/// One chunk, one array-bound INSERT. Every cell is typed from its
/// column's dtype, NULLs included.
fn ingest(session: &Session, insert_sql: &str, ipc_path: &std::path::Path) -> Result<Response> {
    let file = std::fs::File::open(ipc_path)
        .with_context(|| format!("opening chunk {}", ipc_path.display()))?;
    let frame = IpcReader::new(file)
        .finish()
        .map_err(|error| anyhow!("reading chunk ipc: {error}"))?;
    let height = frame.height();
    // Nested columns were created as CLOB and travel as JSON text.
    let columns = frame
        .columns()
        .iter()
        .map(nested_as_json)
        .collect::<Result<Vec<Column>>>()?;
    if columns.is_empty() || height == 0 {
        let _ = std::fs::remove_file(ipc_path);
        let mut response = Response::ok();
        response.rows_affected = Some(0);
        return Ok(response);
    }
    let kinds: Vec<CellKind> = columns.iter().map(|column| cell_kind(column.dtype())).collect();
    let rows: Vec<Vec<Cell>> = (0..height)
        .map(|row| {
            columns
                .iter()
                .map(|column| cell(column, row))
                .collect::<Result<Vec<_>>>()
        })
        .collect::<Result<_>>()?;
    let rows_affected = session.insert_batch(insert_sql, &kinds, &rows)?;
    session.commit()?;
    let _ = std::fs::remove_file(ipc_path);
    let mut response = Response::ok();
    response.rows_affected = Some(rows_affected);
    Ok(response)
}

/// The batch type of a chunk column.
fn cell_kind(dtype: &DataType) -> CellKind {
    match dtype {
        DataType::Boolean
        | DataType::Int8
        | DataType::Int16
        | DataType::Int32
        | DataType::Int64
        | DataType::UInt8
        | DataType::UInt16
        | DataType::UInt32
        | DataType::UInt64 => CellKind::Int,
        DataType::Float32 | DataType::Float64 => CellKind::Float,
        DataType::Decimal(precision, scale) => CellKind::Decimal {
            precision: (*precision).min(38) as u8,
            scale: (*scale).min(38) as i8,
        },
        DataType::Date => CellKind::Date,
        DataType::Datetime(_, None) => CellKind::Timestamp,
        DataType::Datetime(_, Some(_)) => CellKind::TimestampTz,
        DataType::Binary | DataType::BinaryOffset => CellKind::Bytes,
        _ => CellKind::Text,
    }
}

/// One cell as the driver-neutral value the session binds.
fn cell(column: &Column, row: usize) -> Result<Cell> {
    let value = column
        .get(row)
        .map_err(|error| anyhow!("reading {}: {error}", column.name()))?;
    let out_of_range = || anyhow!("timestamp out of range in {}", column.name());
    Ok(match value {
        AnyValue::Null => Cell::Null,
        AnyValue::Boolean(value) => Cell::Int(i64::from(value)),
        AnyValue::Int8(value) => Cell::Int(i64::from(value)),
        AnyValue::Int16(value) => Cell::Int(i64::from(value)),
        AnyValue::Int32(value) => Cell::Int(i64::from(value)),
        AnyValue::Int64(value) => Cell::Int(value),
        AnyValue::UInt8(value) => Cell::Int(i64::from(value)),
        AnyValue::UInt16(value) => Cell::Int(i64::from(value)),
        AnyValue::UInt32(value) => Cell::Int(i64::from(value)),
        AnyValue::UInt64(value) => Cell::Int(value as i64),
        AnyValue::Float32(value) => Cell::Float(f64::from(value)),
        AnyValue::Float64(value) => Cell::Float(value),
        AnyValue::String(value) => Cell::Text(value.to_owned()),
        AnyValue::StringOwned(value) => Cell::Text(value.to_string()),
        AnyValue::Binary(value) => Cell::Bytes(value.to_vec()),
        AnyValue::BinaryOwned(value) => Cell::Bytes(value),
        AnyValue::Date(days) => Cell::Date(date_from_days(days).ok_or_else(out_of_range)?),
        AnyValue::Datetime(value, unit, zone) => {
            timestamp_cell(to_micros(value, unit), zone.is_some()).ok_or_else(out_of_range)?
        }
        AnyValue::DatetimeOwned(value, unit, zone) => {
            timestamp_cell(to_micros(value, unit), zone.is_some()).ok_or_else(out_of_range)?
        }
        // Decimals travel as exact text, parsed by Oracle without rounding.
        AnyValue::Decimal(..) => Cell::Decimal(
            decimal_cell(&value).ok_or_else(|| anyhow!("decimal expected in {}", column.name()))?,
        ),
        AnyValue::Time(nanos) => Cell::Text(time_text(nanos)),
        other => Cell::Text(other.to_string()),
    })
}

/// A zoned column holds instants: its UTC clock goes into TIMESTAMP WITH
/// TIME ZONE; a naive one is the wall clock.
fn timestamp_cell(micros: i64, zoned: bool) -> Option<Cell> {
    let naive = DateTime::from_timestamp_micros(micros)?.naive_utc();
    Some(if zoned {
        Cell::TimestampUtc(naive)
    } else {
        Cell::Timestamp(naive)
    })
}

/// A decimal cell as exact text. polars spells the variant
/// (value, precision, scale) — taking the precision for the scale once
/// turned 111.00 into 0.000000000000011100.
fn decimal_cell(value: &AnyValue) -> Option<String> {
    match value {
        AnyValue::Decimal(unscaled, _precision, scale) => Some(decimal_text(*unscaled, *scale)),
        _ => None,
    }
}

/// A polars time (nanoseconds since midnight) as `HH:MM:SS.ffffff`, the
/// text shape the DDL's VARCHAR2(18) was sized for.
fn time_text(nanos: i64) -> String {
    let micros = nanos.rem_euclid(86_400_000_000_000) / 1_000;
    format!(
        "{:02}:{:02}:{:02}.{:06}",
        micros / 3_600_000_000,
        micros / 60_000_000 % 60,
        micros / 1_000_000 % 60,
        micros % 1_000_000
    )
}

/// A list or struct column as one JSON text per row, via polars' own
/// writer; every other column is returned as it is. The frame is written
/// as JSON lines with the column renamed to a fixed key, so each line is
/// `{"v":…}` and the value is what lies between.
fn nested_as_json(column: &Column) -> Result<Column> {
    if !matches!(column.dtype(), DataType::List(_) | DataType::Struct(_)) {
        return Ok(column.clone());
    }
    let mut frame = DataFrame::new(column.len(), vec![column.clone().with_name("v".into())])
        .map_err(|error| anyhow!("{}: {error}", column.name()))?;
    let mut buffer = Vec::new();
    JsonWriter::new(&mut buffer)
        .with_json_format(JsonFormat::JsonLines)
        .finish(&mut frame)
        .map_err(|error| anyhow!("serialising {}: {error}", column.name()))?;
    let text = String::from_utf8(buffer).context("json is utf-8")?;
    let values = text
        .lines()
        .map(|line| {
            let inner = line
                .strip_prefix("{\"v\":")
                .and_then(|rest| rest.strip_suffix('}'))
                .ok_or_else(|| anyhow!("unexpected json line for {}: {line}", column.name()))?;
            Ok((inner != "null").then(|| inner.to_owned()))
        })
        .collect::<Result<Vec<Option<String>>>>()?;
    if values.len() != column.len() {
        bail!(
            "serialising {}: {} rows became {} json lines",
            column.name(),
            column.len(),
            values.len()
        );
    }
    Ok(Series::new(column.name().clone(), values).into())
}

/// A polars decimal as exact text: the unscaled integer with a decimal
/// point inserted, which Oracle parses into `NUMBER(p,s)` losslessly.
fn decimal_text(value: i128, scale: usize) -> String {
    if scale == 0 {
        return value.to_string();
    }
    let sign = if value < 0 { "-" } else { "" };
    let digits = value.unsigned_abs().to_string();
    let padded = if digits.len() <= scale {
        format!("{}{digits}", "0".repeat(scale + 1 - digits.len()))
    } else {
        digits
    };
    let split = padded.len() - scale;
    format!("{sign}{}.{}", &padded[..split], &padded[split..])
}

fn to_micros(value: i64, unit: TimeUnit) -> i64 {
    match unit {
        TimeUnit::Nanoseconds => value / 1_000,
        TimeUnit::Microseconds => value,
        TimeUnit::Milliseconds => value * 1_000,
    }
}

fn date_from_days(days: i32) -> Option<NaiveDate> {
    NaiveDate::from_num_days_from_ce_opt(days + 719_163)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decimals_and_times_bind_as_exact_text() {
        let amounts = Series::new("A".into(), ["111.00", "-0.05"])
            .cast(&DataType::Decimal(18, 2))
            .unwrap();
        assert_eq!(decimal_cell(&amounts.get(0).unwrap()).unwrap(), "111.00");
        assert_eq!(decimal_cell(&amounts.get(1).unwrap()).unwrap(), "-0.05");
        assert_eq!(decimal_text(1050, 2), "10.50");
        assert_eq!(decimal_text(-5, 2), "-0.05");
        assert_eq!(decimal_text(7, 0), "7");
        assert_eq!(time_text(0), "00:00:00.000000");
        assert_eq!(time_text(45_296_123_456_789), "12:34:56.123456");
    }

    #[test]
    fn cells_carry_their_column_type() {
        let amounts = Series::new("A".into(), ["111.00"])
            .cast(&DataType::Decimal(18, 2))
            .unwrap();
        let column: Column = amounts.into();
        assert_eq!(
            cell_kind(column.dtype()),
            CellKind::Decimal { precision: 18, scale: 2 }
        );
        assert_eq!(cell(&column, 0).unwrap(), Cell::Decimal("111.00".to_owned()));
        let nulls: Column = Series::new("N".into(), [None::<i64>]).into();
        assert_eq!(cell_kind(nulls.dtype()), CellKind::Int);
        assert_eq!(cell(&nulls, 0).unwrap(), Cell::Null);
        let text: Column = Series::new("T".into(), ["héllo"]).into();
        assert_eq!(cell(&text, 0).unwrap(), Cell::Text("héllo".to_owned()));
    }

    #[test]
    fn nested_columns_become_json_text() {
        let list = Series::new(
            "TAGS".into(),
            [Some(vec![1i64, 2]), None, Some(vec![])]
                .into_iter()
                .map(|value| value.map(|items| Series::new("".into(), items)))
                .collect::<Vec<Option<Series>>>(),
        );
        let json = nested_as_json(&list.into()).unwrap();
        assert_eq!(json.dtype(), &DataType::String);
        assert_eq!(json.get(0).unwrap().to_string(), "\"[1,2]\"");
        assert!(json.get(1).unwrap().is_null());
        assert_eq!(json.get(2).unwrap().to_string(), "\"[]\"");
        // Flat columns pass through untouched.
        let flat: Column = Series::new("N".into(), [1i64, 2]).into();
        assert_eq!(nested_as_json(&flat).unwrap().dtype(), &DataType::Int64);
    }
}
