//! The Oracle loader sidecar: drives ODPI-C from this worker process, the
//! only binary Oracle Instant Client is ever loaded into. Same JSON-lines
//! protocol as the Snowflake and DuckDB loaders; every statement it runs
//! is generated by `el_engine::load::oracle_sql` on the parent side.
//!
//! Chunks arrive as Arrow IPC files and are array-bound through the
//! parent's `INSERT … VALUES (:1, :2, …)`: one `Batch` per chunk, one
//! bind type per column set before the first row so an all-NULL column
//! cannot fix the wrong type. The password comes from the environment
//! (`ZDBT_EL_ORACLE_PASSWORD`) and never appears in a request or an error.

use std::io::BufRead as _;

use anyhow::{Context as _, Result, anyhow, bail};
use chrono::{DateTime, NaiveDate, NaiveDateTime, NaiveTime, Utc};
use el_engine::connectors::oracle::{connect, describe_error};
use el_engine::load::protocol::{ENV_ORACLE_PASSWORD, Request, Response};
use el_engine::polars::prelude::*;
use oracle::Connection;
use oracle::sql_type::{OracleType, ToSql};

fn respond(response: &Response) {
    if let Ok(line) = serde_json::to_string(response) {
        println!("{line}");
    }
}

pub fn serve() -> Result<()> {
    let stdin = std::io::stdin();
    let mut connection: Option<Connection> = None;

    for line in stdin.lock().lines() {
        let line = line.context("reading stdin")?;
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        let request: Request = match serde_json::from_str(trimmed) {
            Ok(request) => request,
            Err(error) => {
                respond(&Response::error(format!("bad request: {error}")));
                continue;
            }
        };
        match request {
            Request::Shutdown => {
                respond(&Response::ok());
                break;
            }
            Request::OpenOracle {
                user,
                connect_string,
            } => match open(&user, &connect_string) {
                Ok(conn) => {
                    connection = Some(conn);
                    respond(&Response::ok());
                }
                Err(error) => respond(&Response::error(format!("{error:#}"))),
            },
            Request::Exec { sql } => match &connection {
                Some(conn) => respond(
                    &exec(conn, &sql).unwrap_or_else(|error| Response::error(format!("{error:#}"))),
                ),
                None => respond(&Response::error("not connected — send open first")),
            },
            Request::QueryScalar { sql } => match &connection {
                Some(conn) => respond(
                    &query_scalar(conn, &sql)
                        .unwrap_or_else(|error| Response::error(format!("{error:#}"))),
                ),
                None => respond(&Response::error("not connected — send open first")),
            },
            Request::IngestOracle {
                insert_sql,
                ipc_path,
            } => match &connection {
                Some(conn) => respond(
                    &ingest(conn, &insert_sql, &ipc_path)
                        .unwrap_or_else(|error| Response::error(format!("{error:#}"))),
                ),
                None => respond(&Response::error("not connected — send open first")),
            },
            Request::Open { .. } | Request::OpenDuckdb { .. } | Request::Ingest { .. } => {
                respond(&Response::error(
                    "this is the oracle loader — snowflake and duckdb requests go to \
                     snowflake-loader and duckdb-loader",
                ));
            }
        }
    }
    Ok(())
}

/// Connects with the password the parent put in our environment. The
/// session it returns already pins TIME_ZONE=UTC and a dot decimal
/// separator, which the timestamp binds and the watermark read-back rely on.
fn open(user: &str, connect_string: &str) -> Result<Connection> {
    let password = std::env::var(ENV_ORACLE_PASSWORD)
        .with_context(|| format!("{ENV_ORACLE_PASSWORD} is not set in the sidecar environment"))?;
    connect(user, &password, connect_string)
}

fn exec(connection: &Connection, sql: &str) -> Result<Response> {
    let statement = connection.execute(sql, &[]).map_err(describe_error)?;
    // DDL and PL/SQL blocks commit themselves; DML does not.
    connection.commit().map_err(describe_error)?;
    let mut response = Response::ok();
    response.rows_affected = statement.row_count().ok();
    Ok(response)
}

fn query_scalar(connection: &Connection, sql: &str) -> Result<Response> {
    let mut rows = connection.query(sql, &[]).map_err(describe_error)?;
    let scalar = match rows.next() {
        Some(row) => row
            .map_err(describe_error)?
            .get::<usize, Option<String>>(0)
            .map_err(describe_error)?,
        None => None,
    };
    let mut response = Response::ok();
    response.scalar = scalar.map(serde_json::Value::String);
    Ok(response)
}

/// One chunk, one array-bound INSERT. The whole chunk is already in
/// memory (the parent sized it), so the bind types are chosen from what
/// the column actually holds before any row is appended.
fn ingest(connection: &Connection, insert_sql: &str, ipc_path: &std::path::Path) -> Result<Response> {
    let file = std::fs::File::open(ipc_path)
        .with_context(|| format!("opening chunk {}", ipc_path.display()))?;
    let frame = IpcReader::new(file)
        .finish()
        .map_err(|error| anyhow!("reading chunk ipc: {error}"))?;
    let height = frame.height();
    // Nested columns were created as CLOB and travel as JSON text.
    let columns = frame
        .columns()
        .iter()
        .map(nested_as_json)
        .collect::<Result<Vec<Column>>>()?;
    let columns: Vec<&Column> = columns.iter().collect();
    if columns.is_empty() || height == 0 {
        let _ = std::fs::remove_file(ipc_path);
        let mut response = Response::ok();
        response.rows_affected = Some(0);
        return Ok(response);
    }

    let mut batch = connection
        .batch(insert_sql, height)
        .build()
        .map_err(describe_error)?;
    for (index, column) in columns.iter().enumerate() {
        batch
            .set_type(index + 1, &bind_type(column)?)
            .map_err(describe_error)
            .with_context(|| format!("binding column {}", column.name()))?;
    }
    for row in 0..height {
        let mut values: Vec<Box<dyn ToSql>> = Vec::with_capacity(columns.len());
        for column in &columns {
            values.push(bind_value(column, row)?);
        }
        let refs: Vec<&dyn ToSql> = values.iter().map(|value| value.as_ref()).collect();
        batch.append_row(&refs).map_err(describe_error)?;
    }
    batch.execute().map_err(describe_error)?;
    connection.commit().map_err(describe_error)?;
    let _ = std::fs::remove_file(ipc_path);
    let mut response = Response::ok();
    response.rows_affected = Some(height as u64);
    Ok(response)
}

/// The Oracle bind type for one chunk column. Text and bytes carry a
/// size: a value longer than a `VARCHAR2` bind can hold goes through the
/// LOB path instead (our DDL makes those columns CLOB/BLOB anyway).
fn bind_type(column: &Column) -> Result<OracleType> {
    Ok(match column.dtype() {
        DataType::Boolean
        | DataType::Int8
        | DataType::Int16
        | DataType::Int32
        | DataType::Int64
        | DataType::UInt8
        | DataType::UInt16
        | DataType::UInt32
        | DataType::UInt64 => OracleType::Int64,
        DataType::Float32 | DataType::Float64 => OracleType::BinaryDouble,
        // Decimals bind as their exact text; the session's decimal
        // separator is a dot, so Oracle parses them without loss.
        DataType::Decimal(precision, scale) => {
            OracleType::Number((*precision).min(38) as u8, (*scale).min(38) as i8)
        }
        DataType::Date => OracleType::Date,
        DataType::Datetime(_, None) => OracleType::Timestamp(6),
        DataType::Datetime(_, Some(_)) => OracleType::TimestampTZ(6),
        DataType::Binary | DataType::BinaryOffset => OracleType::BLOB,
        // Oracle has no TIME: the DDL made it VARCHAR2(18) text.
        DataType::Time => OracleType::Varchar2(18),
        DataType::String => {
            let text = column.str().map_err(|error| anyhow!("{error}"))?;
            let (mut widest_bytes, mut widest_chars) = (0usize, 0usize);
            for value in text.iter().flatten() {
                widest_bytes = widest_bytes.max(value.len());
                widest_chars = widest_chars.max(value.chars().count());
            }
            // A VARCHAR2 bind is capped at 4000 BYTES; anything wider is a
            // LOB (and our DDL made that column CLOB).
            if widest_bytes > el_engine::oracle_types::OracleDialect::MAX_VARCHAR2 as usize {
                OracleType::CLOB
            } else {
                OracleType::Varchar2(widest_chars.max(1) as u32)
            }
        }
        other => bail!("column {} has dtype {other} which Oracle cannot load", column.name()),
    })
}

/// One cell as something the driver can bind. Nulls keep the column's
/// type, so a whole-NULL column still lands in the right shape.
fn bind_value(column: &Column, row: usize) -> Result<Box<dyn ToSql>> {
    let value = column
        .get(row)
        .map_err(|error| anyhow!("reading {}: {error}", column.name()))?;
    Ok(match value {
        AnyValue::Null => match column.dtype() {
            DataType::Boolean
            | DataType::Int8
            | DataType::Int16
            | DataType::Int32
            | DataType::Int64
            | DataType::UInt8
            | DataType::UInt16
            | DataType::UInt32
            | DataType::UInt64 => Box::new(None::<i64>),
            DataType::Float32 | DataType::Float64 => Box::new(None::<f64>),
            DataType::Datetime(_, Some(_)) => Box::new(None::<DateTime<Utc>>),
            DataType::Date | DataType::Datetime(_, None) => Box::new(None::<NaiveDateTime>),
            DataType::Binary | DataType::BinaryOffset => Box::new(None::<Vec<u8>>),
            _ => Box::new(None::<String>),
        },
        AnyValue::Boolean(value) => Box::new(i64::from(value)),
        AnyValue::Int8(value) => Box::new(i64::from(value)),
        AnyValue::Int16(value) => Box::new(i64::from(value)),
        AnyValue::Int32(value) => Box::new(i64::from(value)),
        AnyValue::Int64(value) => Box::new(value),
        AnyValue::UInt8(value) => Box::new(i64::from(value)),
        AnyValue::UInt16(value) => Box::new(i64::from(value)),
        AnyValue::UInt32(value) => Box::new(i64::from(value)),
        AnyValue::UInt64(value) => Box::new(value as i64),
        AnyValue::Float32(value) => Box::new(f64::from(value)),
        AnyValue::Float64(value) => Box::new(value),
        AnyValue::String(value) => Box::new(value.to_owned()),
        AnyValue::StringOwned(value) => Box::new(value.to_string()),
        AnyValue::Binary(value) => Box::new(value.to_vec()),
        AnyValue::BinaryOwned(value) => Box::new(value),
        AnyValue::Date(days) => Box::new(
            date_from_days(days)
                .ok_or_else(|| anyhow!("date out of range in {}", column.name()))?,
        ),
        AnyValue::Datetime(value, unit, zone) => {
            let micros = to_micros(value, unit);
            if zone.is_some() {
                Box::new(
                    DateTime::<Utc>::from_timestamp_micros(micros)
                        .ok_or_else(|| anyhow!("timestamp out of range in {}", column.name()))?,
                )
            } else {
                Box::new(
                    DateTime::<Utc>::from_timestamp_micros(micros)
                        .map(|value| value.naive_utc())
                        .ok_or_else(|| anyhow!("timestamp out of range in {}", column.name()))?,
                )
            }
        }
        // Decimals reach the bind as exact text (the column's bind type is
        // NUMBER, so Oracle parses rather than rounds).
        AnyValue::DatetimeOwned(value, unit, zone) => {
            let micros = to_micros(value, unit);
            if zone.is_some() {
                Box::new(
                    DateTime::<Utc>::from_timestamp_micros(micros)
                        .ok_or_else(|| anyhow!("timestamp out of range in {}", column.name()))?,
                )
            } else {
                Box::new(
                    DateTime::<Utc>::from_timestamp_micros(micros)
                        .map(|value| value.naive_utc())
                        .ok_or_else(|| anyhow!("timestamp out of range in {}", column.name()))?,
                )
            }
        }
        AnyValue::Decimal(..) => Box::new(
            decimal_cell(&value).ok_or_else(|| anyhow!("decimal expected in {}", column.name()))?,
        ),
        AnyValue::Time(nanos) => Box::new(time_text(nanos)),
        other => Box::new(other.to_string()),
    })
}

/// A decimal cell as exact text. polars spells the variant
/// (value, precision, scale) — taking the precision for the scale once
/// turned 111.00 into 0.000000000000011100.
fn decimal_cell(value: &AnyValue) -> Option<String> {
    match value {
        AnyValue::Decimal(unscaled, _precision, scale) => Some(decimal_text(*unscaled, *scale)),
        _ => None,
    }
}

/// A polars time (nanoseconds since midnight) as `HH:MM:SS.ffffff`, the
/// text shape the DDL's VARCHAR2(18) was sized for.
fn time_text(nanos: i64) -> String {
    let micros = nanos.rem_euclid(86_400_000_000_000) / 1_000;
    format!(
        "{:02}:{:02}:{:02}.{:06}",
        micros / 3_600_000_000,
        micros / 60_000_000 % 60,
        micros / 1_000_000 % 60,
        micros % 1_000_000
    )
}

/// A list or struct column as one JSON text per row, via polars' own
/// writer; every other column is returned as it is. The frame is written
/// as JSON lines with the column renamed to a fixed key, so each line is
/// `{"v":…}` and the value is what lies between.
fn nested_as_json(column: &Column) -> Result<Column> {
    if !matches!(column.dtype(), DataType::List(_) | DataType::Struct(_)) {
        return Ok(column.clone());
    }
    let mut frame = DataFrame::new(column.len(), vec![column.clone().with_name("v".into())])
        .map_err(|error| anyhow!("{}: {error}", column.name()))?;
    let mut buffer = Vec::new();
    JsonWriter::new(&mut buffer)
        .with_json_format(JsonFormat::JsonLines)
        .finish(&mut frame)
        .map_err(|error| anyhow!("serialising {}: {error}", column.name()))?;
    let text = String::from_utf8(buffer).context("json is utf-8")?;
    let values = text
        .lines()
        .map(|line| {
            let inner = line
                .strip_prefix("{\"v\":")
                .and_then(|rest| rest.strip_suffix('}'))
                .ok_or_else(|| anyhow!("unexpected json line for {}: {line}", column.name()))?;
            Ok((inner != "null").then(|| inner.to_owned()))
        })
        .collect::<Result<Vec<Option<String>>>>()?;
    if values.len() != column.len() {
        bail!(
            "serialising {}: {} rows became {} json lines",
            column.name(),
            column.len(),
            values.len()
        );
    }
    Ok(Series::new(column.name().clone(), values).into())
}

/// A polars decimal as exact text: the unscaled integer with a decimal
/// point inserted, which Oracle parses into `NUMBER(p,s)` losslessly.
fn decimal_text(value: i128, scale: usize) -> String {
    if scale == 0 {
        return value.to_string();
    }
    let sign = if value < 0 { "-" } else { "" };
    let digits = value.unsigned_abs().to_string();
    let padded = if digits.len() <= scale {
        format!("{}{digits}", "0".repeat(scale + 1 - digits.len()))
    } else {
        digits
    };
    let split = padded.len() - scale;
    format!("{sign}{}.{}", &padded[..split], &padded[split..])
}

fn to_micros(value: i64, unit: TimeUnit) -> i64 {
    match unit {
        TimeUnit::Nanoseconds => value / 1_000,
        TimeUnit::Microseconds => value,
        TimeUnit::Milliseconds => value * 1_000,
    }
}

fn date_from_days(days: i32) -> Option<NaiveDateTime> {
    NaiveDate::from_num_days_from_ce_opt(days + 719_163)
        .map(|date| date.and_time(NaiveTime::MIN))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decimals_and_times_bind_as_exact_text() {
        let amounts = Series::new("A".into(), ["111.00", "-0.05"])
            .cast(&DataType::Decimal(18, 2))
            .unwrap();
        assert_eq!(decimal_cell(&amounts.get(0).unwrap()).unwrap(), "111.00");
        assert_eq!(decimal_cell(&amounts.get(1).unwrap()).unwrap(), "-0.05");
        assert_eq!(decimal_text(1050, 2), "10.50");
        assert_eq!(decimal_text(-5, 2), "-0.05");
        assert_eq!(decimal_text(7, 0), "7");
        assert_eq!(time_text(0), "00:00:00.000000");
        assert_eq!(time_text(45_296_123_456_789), "12:34:56.123456");
    }

    #[test]
    fn nested_columns_become_json_text() {
        let list = Series::new(
            "TAGS".into(),
            [Some(vec![1i64, 2]), None, Some(vec![])]
                .into_iter()
                .map(|value| value.map(|items| Series::new("".into(), items)))
                .collect::<Vec<Option<Series>>>(),
        );
        let json = nested_as_json(&list.into()).unwrap();
        assert_eq!(json.dtype(), &DataType::String);
        assert_eq!(json.get(0).unwrap().to_string(), "\"[1,2]\"");
        assert!(json.get(1).unwrap().is_null());
        assert_eq!(json.get(2).unwrap().to_string(), "\"[]\"");
        // Flat columns pass through untouched.
        let flat: Column = Series::new("N".into(), [1i64, 2]).into();
        assert_eq!(nested_as_json(&flat).unwrap().dtype(), &DataType::Int64);
    }
}
