//! The Oracle loader sidecar: drives Oracle's pure-Rust thin driver from
//! this worker process — no Oracle client software anywhere. Same
//! JSON-lines protocol as the Snowflake and DuckDB loaders; every
//! statement it runs is generated by `el_engine::load::oracle_sql` on the
//! parent side.
//!
//! Chunks arrive as Arrow IPC files and are array-bound through the
//! parent's `INSERT … VALUES (:1, :2, …)`: one batch per chunk, every
//! cell typed from its column's dtype (a NULL carries the type too, so an
//! all-NULL column cannot fix the wrong one). The password comes from the
//! environment (`ZDBT_EL_ORACLE_PASSWORD`) and never appears in a request
//! or an error.

use std::io::BufRead as _;

use anyhow::{Context as _, Result, anyhow, bail};
use chrono::{DateTime, Datelike as _, NaiveDate, NaiveDateTime, Timelike as _};
use el_engine::connectors::oracle::{cell_text, connect, describe_error, oracle_timestamp};
use el_engine::load::protocol::{ENV_ORACLE_PASSWORD, Request, Response};
use el_engine::polars::prelude::*;
use oracledb::{BindParameters, Connection, OracleNumber, OracleTimestamp, ToDbValue};

fn respond(response: &Response) {
    if let Ok(line) = serde_json::to_string(response) {
        println!("{line}");
    }
}

pub fn serve() -> Result<()> {
    let stdin = std::io::stdin();
    let mut connection: Option<Connection> = None;

    for line in stdin.lock().lines() {
        let line = line.context("reading stdin")?;
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        let request: Request = match serde_json::from_str(trimmed) {
            Ok(request) => request,
            Err(error) => {
                respond(&Response::error(format!("bad request: {error}")));
                continue;
            }
        };
        match request {
            Request::Shutdown => {
                respond(&Response::ok());
                break;
            }
            Request::OpenOracle {
                user,
                connect_string,
            } => match open(&user, &connect_string) {
                Ok(conn) => {
                    connection = Some(conn);
                    respond(&Response::ok());
                }
                Err(error) => respond(&Response::error(format!("{error:#}"))),
            },
            Request::Exec { sql } => match &connection {
                Some(conn) => respond(
                    &exec(conn, &sql).unwrap_or_else(|error| Response::error(format!("{error:#}"))),
                ),
                None => respond(&Response::error("not connected — send open first")),
            },
            Request::QueryScalar { sql } => match &connection {
                Some(conn) => respond(
                    &query_scalar(conn, &sql)
                        .unwrap_or_else(|error| Response::error(format!("{error:#}"))),
                ),
                None => respond(&Response::error("not connected — send open first")),
            },
            Request::IngestOracle {
                insert_sql,
                ipc_path,
            } => match &connection {
                Some(conn) => respond(
                    &ingest(conn, &insert_sql, &ipc_path)
                        .unwrap_or_else(|error| Response::error(format!("{error:#}"))),
                ),
                None => respond(&Response::error("not connected — send open first")),
            },
            Request::Open { .. } | Request::OpenDuckdb { .. } | Request::Ingest { .. } => {
                respond(&Response::error(
                    "this is the oracle loader — snowflake and duckdb requests go to \
                     snowflake-loader and duckdb-loader",
                ));
            }
        }
    }
    Ok(())
}

/// Connects with the password the parent put in our environment. The
/// session it returns already pins TIME_ZONE=UTC and a dot decimal
/// separator, which the timestamp binds and the watermark read-back rely on.
fn open(user: &str, connect_string: &str) -> Result<Connection> {
    let password = std::env::var(ENV_ORACLE_PASSWORD)
        .with_context(|| format!("{ENV_ORACLE_PASSWORD} is not set in the sidecar environment"))?;
    connect(user, &password, connect_string)
}

fn exec(connection: &Connection, sql: &str) -> Result<Response> {
    let result = connection.execute(sql, &[]).map_err(describe_error)?;
    // DDL and PL/SQL blocks commit themselves; DML does not.
    connection.commit().map_err(describe_error)?;
    let mut response = Response::ok();
    response.rows_affected = Some(result.rows_affected());
    Ok(response)
}

fn query_scalar(connection: &Connection, sql: &str) -> Result<Response> {
    let mut rows = connection.query(sql, &[]).map_err(describe_error)?;
    let scalar = match rows.next() {
        Some(row) => cell_text(&row.map_err(describe_error)?, 0).map_err(describe_error)?,
        None => None,
    };
    let mut response = Response::ok();
    response.scalar = scalar.map(serde_json::Value::String);
    Ok(response)
}

/// One chunk, one array-bound INSERT. Every cell is typed from its
/// column's dtype, NULLs included, so the driver never has to guess a
/// column's type from the first row.
fn ingest(connection: &Connection, insert_sql: &str, ipc_path: &std::path::Path) -> Result<Response> {
    let file = std::fs::File::open(ipc_path)
        .with_context(|| format!("opening chunk {}", ipc_path.display()))?;
    let frame = IpcReader::new(file)
        .finish()
        .map_err(|error| anyhow!("reading chunk ipc: {error}"))?;
    let height = frame.height();
    // Nested columns were created as CLOB and travel as JSON text.
    let columns = frame
        .columns()
        .iter()
        .map(nested_as_json)
        .collect::<Result<Vec<Column>>>()?;
    if columns.is_empty() || height == 0 {
        let _ = std::fs::remove_file(ipc_path);
        let mut response = Response::ok();
        response.rows_affected = Some(0);
        return Ok(response);
    }

    let rows: Vec<Vec<Box<dyn ToDbValue>>> = (0..height)
        .map(|row| {
            columns
                .iter()
                .map(|column| bind_value(column, row))
                .collect::<Result<Vec<_>>>()
        })
        .collect::<Result<_>>()?;
    let refs: Vec<Vec<&dyn ToDbValue>> = rows
        .iter()
        .map(|row| row.iter().map(|value| value.as_ref()).collect())
        .collect();
    let slices: Vec<&[&dyn ToDbValue]> = refs.iter().map(|row| row.as_slice()).collect();
    let result = connection
        .execute_batch(insert_sql, BindParameters::Slice(&slices))
        .map_err(describe_error)?;
    connection.commit().map_err(describe_error)?;
    let _ = std::fs::remove_file(ipc_path);
    let mut response = Response::ok();
    response.rows_affected = Some(result.rows_affected());
    Ok(response)
}

/// One cell as something the driver can bind. A NULL is typed by the
/// column's dtype, so a whole-NULL column still lands in the right shape.
fn bind_value(column: &Column, row: usize) -> Result<Box<dyn ToDbValue>> {
    let value = column
        .get(row)
        .map_err(|error| anyhow!("reading {}: {error}", column.name()))?;
    let out_of_range = || anyhow!("timestamp out of range in {}", column.name());
    Ok(match value {
        AnyValue::Null => match column.dtype() {
            DataType::Boolean
            | DataType::Int8
            | DataType::Int16
            | DataType::Int32
            | DataType::Int64
            | DataType::UInt8
            | DataType::UInt16
            | DataType::UInt32
            | DataType::UInt64 => Box::new(None::<i64>),
            DataType::Float32 | DataType::Float64 => Box::new(None::<f64>),
            DataType::Decimal(..) => Box::new(None::<OracleNumber>),
            DataType::Date | DataType::Datetime(..) => Box::new(None::<OracleTimestamp>),
            DataType::Binary | DataType::BinaryOffset => Box::new(None::<Vec<u8>>),
            _ => Box::new(None::<String>),
        },
        AnyValue::Boolean(value) => Box::new(i64::from(value)),
        AnyValue::Int8(value) => Box::new(i64::from(value)),
        AnyValue::Int16(value) => Box::new(i64::from(value)),
        AnyValue::Int32(value) => Box::new(i64::from(value)),
        AnyValue::Int64(value) => Box::new(value),
        AnyValue::UInt8(value) => Box::new(i64::from(value)),
        AnyValue::UInt16(value) => Box::new(i64::from(value)),
        AnyValue::UInt32(value) => Box::new(i64::from(value)),
        AnyValue::UInt64(value) => Box::new(value as i64),
        AnyValue::Float32(value) => Box::new(f64::from(value)),
        AnyValue::Float64(value) => Box::new(value),
        AnyValue::String(value) => Box::new(value.to_owned()),
        AnyValue::StringOwned(value) => Box::new(value.to_string()),
        AnyValue::Binary(value) => Box::new(value.to_vec()),
        AnyValue::BinaryOwned(value) => Box::new(value),
        AnyValue::Date(days) => {
            let date = date_from_days(days).ok_or_else(out_of_range)?;
            Box::new(OracleTimestamp::new_date(
                date.year() as i16,
                date.month() as u8,
                date.day() as u8,
            ))
        }
        AnyValue::Datetime(value, unit, zone) => {
            timestamp_bind(to_micros(value, unit), zone.is_some()).ok_or_else(out_of_range)?
        }
        AnyValue::DatetimeOwned(value, unit, zone) => {
            timestamp_bind(to_micros(value, unit), zone.is_some()).ok_or_else(out_of_range)?
        }
        // Decimals reach the driver as exact text, parsed into its own
        // NUMBER representation without rounding.
        AnyValue::Decimal(..) => Box::new(
            decimal_cell(&value)
                .ok_or_else(|| anyhow!("decimal expected in {}", column.name()))?
                .parse::<OracleNumber>()
                .map_err(describe_error)?,
        ),
        AnyValue::Time(nanos) => Box::new(time_text(nanos)),
        other => Box::new(other.to_string()),
    })
}

/// A zoned column holds instants: bind the UTC clock with a zero offset
/// into TIMESTAMP WITH TIME ZONE; a naive one binds as the wall clock.
fn timestamp_bind(micros: i64, zoned: bool) -> Option<Box<dyn ToDbValue>> {
    let naive = DateTime::from_timestamp_micros(micros)?.naive_utc();
    Some(if zoned {
        Box::new(zoned_utc(naive))
    } else {
        Box::new(oracle_timestamp(naive))
    })
}

fn zoned_utc(value: NaiveDateTime) -> OracleTimestamp {
    OracleTimestamp::new_timestamp_tz(
        value.year() as i16,
        value.month() as u8,
        value.day() as u8,
        value.hour() as u8,
        value.minute() as u8,
        value.second() as u8,
        value.nanosecond(),
        0,
        0,
    )
}

/// A decimal cell as exact text. polars spells the variant
/// (value, precision, scale) — taking the precision for the scale once
/// turned 111.00 into 0.000000000000011100.
fn decimal_cell(value: &AnyValue) -> Option<String> {
    match value {
        AnyValue::Decimal(unscaled, _precision, scale) => Some(decimal_text(*unscaled, *scale)),
        _ => None,
    }
}

/// A polars time (nanoseconds since midnight) as `HH:MM:SS.ffffff`, the
/// text shape the DDL's VARCHAR2(18) was sized for.
fn time_text(nanos: i64) -> String {
    let micros = nanos.rem_euclid(86_400_000_000_000) / 1_000;
    format!(
        "{:02}:{:02}:{:02}.{:06}",
        micros / 3_600_000_000,
        micros / 60_000_000 % 60,
        micros / 1_000_000 % 60,
        micros % 1_000_000
    )
}

/// A list or struct column as one JSON text per row, via polars' own
/// writer; every other column is returned as it is. The frame is written
/// as JSON lines with the column renamed to a fixed key, so each line is
/// `{"v":…}` and the value is what lies between.
fn nested_as_json(column: &Column) -> Result<Column> {
    if !matches!(column.dtype(), DataType::List(_) | DataType::Struct(_)) {
        return Ok(column.clone());
    }
    let mut frame = DataFrame::new(column.len(), vec![column.clone().with_name("v".into())])
        .map_err(|error| anyhow!("{}: {error}", column.name()))?;
    let mut buffer = Vec::new();
    JsonWriter::new(&mut buffer)
        .with_json_format(JsonFormat::JsonLines)
        .finish(&mut frame)
        .map_err(|error| anyhow!("serialising {}: {error}", column.name()))?;
    let text = String::from_utf8(buffer).context("json is utf-8")?;
    let values = text
        .lines()
        .map(|line| {
            let inner = line
                .strip_prefix("{\"v\":")
                .and_then(|rest| rest.strip_suffix('}'))
                .ok_or_else(|| anyhow!("unexpected json line for {}: {line}", column.name()))?;
            Ok((inner != "null").then(|| inner.to_owned()))
        })
        .collect::<Result<Vec<Option<String>>>>()?;
    if values.len() != column.len() {
        bail!(
            "serialising {}: {} rows became {} json lines",
            column.name(),
            column.len(),
            values.len()
        );
    }
    Ok(Series::new(column.name().clone(), values).into())
}

/// A polars decimal as exact text: the unscaled integer with a decimal
/// point inserted, which Oracle parses into `NUMBER(p,s)` losslessly.
fn decimal_text(value: i128, scale: usize) -> String {
    if scale == 0 {
        return value.to_string();
    }
    let sign = if value < 0 { "-" } else { "" };
    let digits = value.unsigned_abs().to_string();
    let padded = if digits.len() <= scale {
        format!("{}{digits}", "0".repeat(scale + 1 - digits.len()))
    } else {
        digits
    };
    let split = padded.len() - scale;
    format!("{sign}{}.{}", &padded[..split], &padded[split..])
}

fn to_micros(value: i64, unit: TimeUnit) -> i64 {
    match unit {
        TimeUnit::Nanoseconds => value / 1_000,
        TimeUnit::Microseconds => value,
        TimeUnit::Milliseconds => value * 1_000,
    }
}

fn date_from_days(days: i32) -> Option<NaiveDate> {
    NaiveDate::from_num_days_from_ce_opt(days + 719_163)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decimals_and_times_bind_as_exact_text() {
        let amounts = Series::new("A".into(), ["111.00", "-0.05"])
            .cast(&DataType::Decimal(18, 2))
            .unwrap();
        assert_eq!(decimal_cell(&amounts.get(0).unwrap()).unwrap(), "111.00");
        assert_eq!(decimal_cell(&amounts.get(1).unwrap()).unwrap(), "-0.05");
        assert_eq!(decimal_text(1050, 2), "10.50");
        assert_eq!(decimal_text(-5, 2), "-0.05");
        assert_eq!(decimal_text(7, 0), "7");
        assert_eq!(time_text(0), "00:00:00.000000");
        assert_eq!(time_text(45_296_123_456_789), "12:34:56.123456");
    }

    #[test]
    fn nested_columns_become_json_text() {
        let list = Series::new(
            "TAGS".into(),
            [Some(vec![1i64, 2]), None, Some(vec![])]
                .into_iter()
                .map(|value| value.map(|items| Series::new("".into(), items)))
                .collect::<Vec<Option<Series>>>(),
        );
        let json = nested_as_json(&list.into()).unwrap();
        assert_eq!(json.dtype(), &DataType::String);
        assert_eq!(json.get(0).unwrap().to_string(), "\"[1,2]\"");
        assert!(json.get(1).unwrap().is_null());
        assert_eq!(json.get(2).unwrap().to_string(), "\"[]\"");
        // Flat columns pass through untouched.
        let flat: Column = Series::new("N".into(), [1i64, 2]).into();
        assert_eq!(nested_as_json(&flat).unwrap().dtype(), &DataType::Int64);
    }
}
